{application,chat,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{chat_app,[]}},
              {env,[]},
              {modules,[chat_app,chat_client_fsm,chat_server,chat_sup,
                        chat_user_sup]}]}.
